<?php 

function updateProducts($currency, $xchange_rate) {

	//load product collection
	$product_collection  = Mage::getModel('catalog/product')->getCollection()
		->addAttributeToSelect('*')
		->addFieldToFilter(
			'currency',
			array(
				'eq' => Mage::getResourceModel('catalog/product')
							->getAttribute('currency')
							->getSource()
							->getOptionId($currency)
			)
		);
														   
	$num = 0;
	foreach($product_collection as $product) {
			
		$num++;
		
		//print_r($product->getData());
		
		echo"<b>Aktualisierte Produkte:</b><br>";
		
		//attributes for user information
		$id = $product->getResource()->getAttribute('entity_id')->getFrontend()->getValue($product);
		$name = $product->getResource()->getAttribute('name')->getFrontend()->getValue($product);
		
		//attributes for price calculation
		$basis_price = $product->getResource()->getAttribute('basis_preis')->getFrontend()->getValue($product);
		$shippingcost = $product->getResource()->getAttribute('versandkosten')->getFrontend()->getValue($product);	
		//echo $shippingcost;exit;
		//calulation of new price
		
		
		$new_price = $basis_price / $xchange_rate + $shippingcost;
		
		
		//information for user
		$output = $num." - #".$id."|".$name." - ".$basis_price." => ".$new_price. " AUD";
		
		if ($shippingcost != '')
		{
			$output = $output." (inkl. Versand ". round($shippingcost,2)." AUD)"; 
		} 
		echo $output."<br>";
	   
	   //updating product price
	   $product->setPrice($new_price)
			   ->save(); 	
		
	}     
	echo "<b>Aktualisierter Produkte </b>".$num; //update Products
	echo "<br><br>";
}



$collection = Mage::getModel('product/product')->getCollection();


echo "<pre>";
print_r($collection->getData());
echo "</pre>";


		
		foreach($collection as $row) {
	    		//$collection_r[] = $row['Pfund'];
		
		//$collection = $collection_r;

if (($row['Pfund'] !='') AND ($row['Euro']!=''))
	{
		echo "<b>Pfund :</b>".$row['Pfund']."<br>".
		"<b>Euro :</b>".$row['Euro']."<br>".
		"<b>Dollar :</b>".$row['USD']."<br>";
		echo "<br><br>";
		
		echo"<h3>Pfund</h3>";
		$demo = updateProducts('Pfund', $row['Pfund']);
		
		echo"<h3>Euro</h3>";
		updateProducts('Euro', $row['Euro']);
		
		echo"<h3>US Dollar</h3>";
		updateProducts('USD', $row['USD']);
		
		echo"<h3>Australische Dollar</h3>";
		updateProducts('dollar',15); //xchange rate is 1:1 but shipping cost need to be updated
		
		//inform Admin about update
		//informEmail('martin.steudter@konvis.de');
	}
		}
		

?>